### ISSUE TITLE
But why is that port open in the first place ? Also won't that require port forwarding from the target device router to work ?!... which clueless users won't do.

### ISSUE THREAD

**Issue by minanagehsalalma** [manjingero/zugzwang#1]

**Comment by manjingero** [comment]
The port is automatically opened with the installation of the tweak "openSSH". That tweak gets automatically installed upon jailbreaking with certain tools.

**Comment by minanagehsalalma** [comment]
> installed upon jailbreaking with certain tools.

@manjingero  like ?

**Comment by LjMario007** [comment]
yalu, electra, etc.

**Comment by minanagehsalalma** [comment]
@LjMario007 never heard of them are they for ios or what? 

Also they didn't answer the port forwarding part... routers wouldn't allow such connections !
